name: CI

on: ['push', 'pull_request']

jobs:
  build-and-test:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    environment: Bintray

    strategy:
      matrix:
        java: [11, 15]

    env:
      TEST_ALL_CONTAINERS: "['tomcat10','jetty11']"
      GRADLE_VERSION: 6.8.3
      GECKO_DRIVER_VERSION: 0.28.0
      BINTRAY_REPO: maven
      BINTRAY_PACKAGE: org.gretty

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Gradle stuff
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches/modules-2
          key: ${{ runner.os }}-build-${{ env.GRADLE_VERSION }}-${{ hashFiles('**/*.gradle', 'gradle.properties') }}

      - name: Build and Test
        run: |
          set -e
          ./gradlew --no-daemon wrapper --gradle-version $GRADLE_VERSION --distribution-type all
          ./gradlew --no-daemon --warning-mode all build
          cd integrationTests
          ../gradlew --no-daemon --warning-mode all -PgeckoDriverPlatform=linux64 -PgeckoDriverVersion=$GECKO_DRIVER_VERSION -PtestAllContainers=$TEST_ALL_CONTAINERS testAll
          cd ..
          set +e
